// Publish project specific data
(function() {
rh = window.rh;
model = rh.model;

rh.consts('DEFAULT_TOPIC', encodeURI("#Manual_de_usuario.htm".substring(1)));
rh.consts('START_FILEPATH', encodeURI('index.htm'));
rh.consts('HELP_ID', '25220B49-8992-429F-9729-462C6DA25C9C' || 'preview');
rh.consts('LNG_STOP_WORDS', ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "a", "aceptar", "ahí", "alguna", "algunas", "alguno", "algunos", "aquí", "aún", "cada", "como", "cómo", "con", "cuál", "cualquier", "cualquiera", "cuando", "cuándo", "de", "deber", "dentro", "desde", "después", "dónde", "el", "él", "ella", "ello", "ellos", "en", "entonces", "entre", "era", "eran", "es", "esos", "esto", "estos", "forma", "hacer", "hacia", "hecho", "igual", "junto", "la", "lo", "los", "más", "necesitar", "ninguno", "no", "nosotros", "ó", "o", "otra", "otro", "otroa", "para", "pero", "poder", "por", "porque", "puede", "qué", "que", "queremos", "re", "ser", "si", "sido", "sin", "son", "soy", "sus", "también", "tan", "tener", "tiene", "todo", "Todo", "Todos", "todos", "tu", "tus", "u", "un", "una", "uno", "usado", "usando", "usar", "usted", "ustedes", "utilizando", "utilizar", "ver", "vosotros", "y", "ya", "Yo"]);
rh.consts('LNG_SUBSTR_SEARCH', 1);

model.publish(rh.consts('KEY_DIR'), "ltr");
model.publish(rh.consts('KEY_LNG'), { "SearchResultsPerScreen" : "Resultados de búsqueda por página", "Reset" : "Restablecer", "SyncToc" : "Sincronizar TOC", "HomeButton" : "Inicio", "WebSearchButton" : "WebSearch", "GlossaryFilterTerms" : "Encontrar término", "HighlightSearchResults" : "Resaltar resultados de búsqueda", "ApplyTip" : "Aplicar", "WebSearch" : "WebSearch", "Show" : "Mostrar", "ShowAll" : "Mostrar todo", "EnableAndSearch" : "Mostrar resultados que incluyan todas las palabras de búsqueda", "Next" : ">>", "PreviousLabel" : "Anterior", "NoScriptErrorMsg" : "Active la compatibilidad con JavaScript en el explorador para ver esta página.", "Print" : "Imprimir", "Contents" : "Contenido", "Search" : "Búsqueda", "Hide" : "Ocultar", "Canceled" : "Cancelado", "ShowHide" : "Mostrar/Ocultar", "Loading" : "Cargando...", "EndOfResults" : "Fin de resultados de búsqueda.", "Logo" : "Logotipo", "ContentFilterChanged" : "Se ha cambiado el filtro de contenido, vuelva a buscar", "SidebarToggleTip" : "Expandir/colapsar", "Logo/Author" : "Desarrollado por", "JS_alert_LoadXmlFailed" : "Error: no se pudo cargar el archivo xml.", "Searching" : "Buscando...", "SearchTitle" : "Buscar", "Disabled Next" : ">>", "JS_alert_InitDatabaseFailed" : "Error: no se pudo inicializar la base de datos.", "Cancel" : "Cancelar", "UnknownError" : "Error desconocido", "ResultsFoundText" : "%1 resultado(s) encontrado(s) para %2", "Index" : "Índice", "Seperate" : "|", "SearchPageTitle" : "Resultados de búsqueda", "TopicsNotFound" : "No se han encontrado temas.", "Glossary" : "Glosario", "Filter" : "Filtrar", "NextLabel" : "Siguiente", "TableOfContents" : "Tabla de contenido", "HideAll" : "Ocultar todo", "Disabled Prev" : "<<", "SearchOptions" : "Opciones de búsqueda", "Back" : "Atrás", "Prev" : "<<", "OpenLinkInNewTab" : "Abrir en nueva ficha", "JS_alert_InvalidExpression_1" : "Las palabras que ha escrito no son una expresión válida.", "IndexFilterKewords" : "Encontrar palabra clave", "IeCompatibilityErrorMsg" : "Esta página no se puede ver en Internet Explorer 8 o versiones anteriores.", "NavTip" : "Menú", "ToTopTip" : "Ir al principio" });
})();